export const marketingFeatures = [
  {
    slug: "ai-clipper",
    href: "/clipper",
    eyebrow: "Long video to short clips",
    seoTitle: "AI Clipper for Videos, Podcasts and Social Shorts",
    cardTitle: "AI Clipper",
    title: "AI Clipper that finds the moments worth sharing",
    description: "Paste a supported public video link or upload long footage, then let AI rank the strongest hooks and turn selected moments into captioned, platform-ready clips.",
    keywords: ["AI clipper", "AI video clipper", "long video to shorts", "podcast clip maker", "video highlight generator"],
    answer: {
      question: "What is Editing App's AI Clipper?",
      summary: "It securely imports a supported video link or private upload, transcribes the footage, ranks self-contained high-retention moments, and prepares editable clips for Shorts, Reels, and TikTok.",
      bestFor: "Podcasts, interviews, webinars, tutorials, product demos, and campaign footage.",
      input: "A supported public video link or private upload plus the analysis model you choose.",
      output: "Ranked moments, editable clip ranges, captions, social formats, and private MP4 exports.",
    },
    benefits: ["Video-link and resumable upload inputs", "AI-ranked hooks and standalone moments", "One-click moment-to-clip selection", "Editable captions and 9:16, 1:1, or 16:9 formats", "Durable private processing for long footage"],
    workflow: ["Paste a supported video link or upload a file", "Choose Autopilot or a specific analysis model", "Select a ranked moment and refine the clip", "Export a private social-ready MP4"],
    faq: [
      { question: "Which video links can I import?", answer: "AI Clipper accepts public YouTube, Vimeo, TikTok, Instagram, Facebook, and X video links up to 60 minutes, subject to platform availability. You must own the video or have permission to reuse it." },
      { question: "Can I choose the analysis model?", answer: "Yes. Use Clipper Autopilot or select an approved GPT, Gemini, or local analysis option before re-analysis." },
      { question: "How does it choose the best moments?", answer: "The workflow combines transcript meaning, scene boundaries, pacing, silence detection, and an AI ranking model to identify hooks that can stand alone as short-form clips." },
      { question: "Can I adjust a selected moment?", answer: "Yes. Selecting a ranked moment sets the clip range, but trim, cleanup, captions, framing, visual style, and audio remain editable before export." },
    ],
  },
  {
    slug: "ai-video-generator",
    href: "/generate/video",
    eyebrow: "Multi-model video generation",
    seoTitle: "AI Video Generator with Premium Models",
    cardTitle: "AI video generator",
    title: "AI video generation with the right model for every shot",
    description: "Direct camera movement, mood, aspect ratio, duration, native audio, and resolution, then choose Seedance, LTX, Veo, Kling, or let Model Autopilot route the brief.",
    keywords: ["AI video generator", "text to video AI", "image to video AI", "Seedance video generator", "Veo video generator"],
    answer: {
      question: "What does the multi-model AI video generator do?",
      summary: "It turns a production brief into a private AI-generated video and lets creators choose a compatible Seedance, LTX, Veo, or Kling model instead of hiding every job behind one generic generator.",
      bestFor: "Creators, ecommerce teams, agencies, and editors producing cinematic or commercial shots.",
      input: "A text or image-led production brief with camera, mood, format, duration, and audio choices.",
      output: "A model-compatible private video master with validated duration and resolution settings.",
    },
    benefits: ["Seedance 2.5 shots up to 30 seconds at supported resolution", "Native 4K with supported LTX 2.3 Pro and Veo workflows", "Native audio on compatible models", "Server-side capability validation before paid generation", "Private delivery checkpoints prevent duplicate paid renders on retry"],
    workflow: ["Write a production brief", "Choose a model or routing intent", "Select only compatible duration and resolution controls", "Download the private master"],
    faq: [
      { question: "Does every model support 4K and 30 seconds?", answer: "No. Controls adapt to the selected model. Seedance supports longer shots at its available resolution, while supported LTX and Veo routes provide native 4K for shorter clips." },
      { question: "What does Model Autopilot do?", answer: "It ranks approved models by quality, reliability, speed, and cost, then selects only from models compatible with the requested duration and resolution." },
      { question: "Can AI video include generated audio?", answer: "Yes, when the selected provider supports native audio. The interface exposes audio only for compatible models and validates the request again on the server." },
      { question: "How does Editing App avoid duplicate paid renders?", answer: "Durable job checkpoints record the provider request and delivered output so a delivery retry does not silently start the same paid generation again." },
    ],
  },
  {
    slug: "ai-image-generator",
    href: "/generate/image",
    eyebrow: "Campaign-ready image generation",
    seoTitle: "AI Image Generator with Premium Models",
    cardTitle: "AI image generator",
    title: "AI image generator with art direction and premium model choice",
    description: "Create product, editorial, photoreal, cinematic, and illustrated visuals with Seedream, Recraft, Nano Banana, and FLUX models in one controlled workflow.",
    keywords: ["AI image generator", "AI product image generator", "AI ad image generator", "Seedream image generator", "Recraft AI image generator"],
    answer: {
      question: "What makes this AI image generator different?",
      summary: "Editing App combines premium image models with explicit art direction, canvas, seed, and routing controls so users can create repeatable campaign visuals instead of relying on an unexplained one-prompt workflow.",
      bestFor: "Product imagery, paid-social graphics, editorial concepts, brand design, and campaign exploration.",
      input: "A visual brief, canvas, art direction, optional seed, and a selected image model or Autopilot.",
      output: "A privately delivered campaign image generated with the chosen compatible model.",
    },
    benefits: ["Seedream 5.0 Pro and Lite", "Recraft V4.1 Pro for brand design", "Nano Banana 2 for instruction fidelity", "FLUX.2 Max and Turbo", "Canvas, art direction, seed, and routing controls"],
    workflow: ["Describe the visual outcome", "Choose an image model or Autopilot", "Set art direction and canvas", "Review the routed private result"],
    faq: [
      { question: "Can I choose a specific image model?", answer: "Yes. Every listed model is allowlisted on the server, or you can use Image Autopilot for a fresh routing decision." },
      { question: "Are generated images public?", answer: "No. Inputs and completed outputs use private storage with time-limited access links." },
      { question: "Which model is best for product and brand graphics?", answer: "Recraft V4.1 Pro is positioned for controlled commercial and brand design, while Seedream, Nano Banana, and FLUX routes cover photoreal, instruction-led, and rapid exploration workflows." },
      { question: "Can I control the canvas and creative direction?", answer: "Yes. The generation brief includes canvas, style, seed, and art-direction controls instead of relying on a single unexplained prompt box." },
    ],
  },
  {
    slug: "ai-image-ad-creator",
    href: "/creative-studio/image",
    eyebrow: "Static ads for online and local business",
    seoTitle: "AI Image Ad Creator for Products & Local Business",
    cardTitle: "AI image ad creator",
    title: "AI image ads designed for the placement and the offer",
    description: "Turn a product URL or real local-business brief into source-aware image ads for Facebook, Instagram, TikTok, and YouTube with platform sizing, readable hierarchy, and claim guardrails.",
    keywords: ["AI image ad creator", "AI image ad generator", "local business ad generator", "product image ad generator", "social media ad creator"],
    answer: {
      question: "What does Editing App's AI image ad creator do?",
      summary: "It turns an ecommerce product page or local-business brief into a grounded campaign plan and private platform-ready image advertisement.",
      bestFor: "Online stores, restaurants, clinics, salons, real-estate teams, local services, performance marketers, and agencies.",
      input: "A public product page or real business brief plus the audience, platform, offer, message, and call to action.",
      output: "A source-aware conversion brief and private image ad sized for the selected social placement.",
    },
    benefits: ["Product URL image composition", "Local-business ads without a store URL", "Facebook, Instagram, TikTok, and YouTube sizing", "Readable hierarchy and CTA direction", "Guardrails against unsupported claims"],
    workflow: ["Add a product URL or local-business brief", "Choose the platform and audience", "Select an image-ad model", "Generate the private campaign image"],
    faq: [
      { question: "Can a local business create an image ad without a product URL?", answer: "Yes. Add the real business name, service, location, audience, message, and CTA to create a platform-sized campaign image." },
      { question: "Which platforms are supported?", answer: "Facebook, Instagram, TikTok, and YouTube are available with platform-aware image placements." },
      { question: "Will it invent contact details or product claims?", answer: "The workflow blocks unsupported prices, discounts, reviews, guarantees, contact details, ingredients, and performance claims." },
      { question: "Can I choose the image-ad model?", answer: "Yes. Choose a compatible product composer, brand designer, campaign designer, photoreal director, or use Ad Creative Autopilot." },
    ],
  },
  {
    slug: "ai-video-ad-creator",
    href: "/creative-studio/video",
    eyebrow: "Motion ads for ecommerce and social",
    seoTitle: "AI Video Ad Creator for Ecommerce & Social",
    cardTitle: "AI video ad creator",
    title: "AI video ads with source-aware hooks and platform pacing",
    description: "Turn a product URL or analyzed long video into a source-aware video ad for Facebook, Instagram, TikTok, or YouTube with selectable premium models, native audio, and private delivery.",
    keywords: ["AI video ad creator", "AI video ad generator", "product URL to video ad", "ecommerce video ad generator", "social media video ad creator"],
    answer: {
      question: "What does Editing App's AI video ad creator do?",
      summary: "It turns product-page context or an owned analyzed video into a conversion brief and private platform-ready motion advertisement.",
      bestFor: "Ecommerce brands, DTC teams, performance marketers, content teams, and agencies producing paid-social video.",
      input: "A public product page or analyzed private video plus the audience, platform, message, and call to action.",
      output: "A grounded conversion brief and private video ad with platform-aware framing, pacing, and model selection.",
    },
    benefits: ["Product URL to video-ad direction", "Long-video hook repurposing", "Seedance and Veo ad directors", "Platform-aware pacing and formats", "Paid-render checkpoints prevent duplicate charges"],
    workflow: ["Add a product URL or analyzed video", "Choose the platform and audience", "Select a video-ad model", "Generate the private motion creative"],
    faq: [
      { question: "Can I turn a product URL directly into a video ad?", answer: "Yes. The studio uses available product-page context and media with your audience, platform, message, and CTA controls." },
      { question: "Can I reuse a long video?", answer: "Yes. The video-ad workflow can identify a promising hook in an analyzed project and prepare short-form creative direction for the selected platform." },
      { question: "Which platforms are supported?", answer: "Facebook, Instagram, TikTok, and YouTube are available with platform-aware video placements, aspect ratios, and pacing." },
      { question: "Can I choose the video model?", answer: "Yes. Choose an approved Seedance or Veo ad director, a long-video scout, or use Ad Creative Autopilot." },
    ],
  },
  {
    slug: "background-remover",
    href: "/remove-background",
    eyebrow: "Precision cutouts",
    seoTitle: "AI Background Remover for Products",
    cardTitle: "AI background remover",
    title: "AI background remover for people, products, and fine edges",
    description: "Remove image backgrounds with precision or speed agents, private uploads, transparent PNG output, and edge-aware model routing.",
    keywords: ["AI background remover", "remove image background", "product background remover", "transparent PNG maker", "background removal AI"],
    answer: {
      question: "How does the AI background remover work?",
      summary: "It routes a private product or portrait image to a precision or speed model, separates the foreground, and delivers a transparent PNG while preserving fine edges such as hair and soft product detail.",
      bestFor: "Ecommerce products, portraits, catalog images, thumbnails, and campaign cutouts.",
      input: "A private JPEG, PNG, or WebP image and a precision, speed, or Autopilot choice.",
      output: "A private transparent PNG with edge-aware foreground separation.",
    },
    benefits: ["BiRefNet V2 precision matting", "Fast Rembg option", "Hair and soft-edge preservation", "Transparent PNG delivery", "Private source and output storage"],
    workflow: ["Upload a JPEG, PNG, or WebP", "Choose precision, speed, or Autopilot", "Run the private cutout job", "Download the transparent PNG"],
    faq: [
      { question: "Which model should I choose?", answer: "Use BiRefNet V2 for hair, products, and fine edges; use Rembg Fast for clean, simple subjects; or let Autopilot decide." },
      { question: "What output format is delivered?", answer: "The completed cutout is stored privately and delivered as a transparent PNG." },
      { question: "Which image formats can I upload?", answer: "The background-removal workflow accepts JPEG, PNG, and WebP source images after server-side validation." },
      { question: "Are the original and cutout images public?", answer: "No. Source files and completed results stay in private storage and are accessed through short-lived signed links." },
    ],
  },
] as const;

export type MarketingFeature = (typeof marketingFeatures)[number];

export function getMarketingFeature(slug: string) {
  return marketingFeatures.find((feature) => feature.slug === slug);
}
