export const searchIntentPages = [
  {
    slug: "product-url-to-video",
    eyebrow: "Product URL to video",
    seoTitle: "Product URL to Video Ad Generator",
    title: "Product URL to video ad generator for ecommerce brands",
    description: "Turn a product page into a source-aware video ad for Facebook, Instagram, TikTok, or YouTube with selectable Seedance and Veo creative agents.",
    keywords: ["product URL to video", "URL to video ad", "AI video ad generator", "ecommerce video ads", "product video generator"],
    answer: {
      question: "Can AI turn a product URL into a video ad?",
      summary: "Yes. Editing App reads usable product facts and images from a public product page, combines them with your audience and channel choices, and prepares a source-aware video ad without inventing unsupported claims.",
      bestFor: "Shopify launches, DTC creative testing, agency campaigns, and ecommerce catalog refreshes.",
      input: "A public product URL, target audience, platform, message, and call to action.",
      output: "A grounded ad brief and platform-ready video creative for Meta, Instagram, TikTok, or YouTube.",
    },
    intro: "Paste a product URL, choose the audience and channel, and create a production brief grounded in the page's real images and product details. Editing App blocks unsupported claims before the paid render starts.",
    primaryHref: "/login?mode=signup",
    primaryLabel: "Create a product ad",
    featureHref: "/creative-studio/video",
    outcomes: [
      "Source-aware scripts that use product-page facts",
      "Platform-specific framing for paid and organic placements",
      "Seedance 2.5 or Veo 3.1 ad-direction options",
      "Clear audience, hook, offer, and call-to-action controls",
    ],
    steps: [
      "Paste a public product URL and let the studio collect usable product context.",
      "Choose Facebook, Instagram, TikTok, or YouTube and define the audience.",
      "Select an ad director, review the source-aware brief, and generate the creative.",
      "Download the platform-ready master and create measured hook variations.",
    ],
    useCases: ["Shopify product launches", "DTC creative testing", "Agency client campaigns", "Catalog refreshes"],
    faq: [
      { question: "What does the AI read from a product URL?", answer: "The workflow uses available page metadata and media as source context for the creative brief. It does not treat page instructions as trusted application commands." },
      { question: "Can the generator invent a discount or customer review?", answer: "No. The planning guardrails block unsupported prices, discounts, guarantees, reviews, ingredients, and performance claims." },
      { question: "Which social platforms are supported?", answer: "Facebook, Instagram, TikTok, and YouTube are available with platform-aware placements, aspect ratios, pacing, and calls to action." },
      { question: "Can I choose the video model?", answer: "Yes. Choose an approved Seedance or Veo ad director, or use the source-aware routing option when available." },
    ],
  },
  {
    slug: "long-video-to-shorts",
    eyebrow: "Long video to shorts",
    seoTitle: "Long Video to Shorts AI Clipper",
    title: "Turn long videos into short clips with AI Clipper",
    description: "Analyze long footage, find strong hooks, build captions, and prepare editable vertical clips for TikTok, Instagram Reels, YouTube Shorts, and Facebook.",
    keywords: ["long video to shorts", "AI clip maker", "podcast clip generator", "YouTube to Shorts", "video highlight generator"],
    answer: {
      question: "How do you turn a long video into short clips with AI?",
      summary: "Upload the long video, choose an analysis model, review ranked hooks and transcript-based suggestions, then refine captions, framing, and timing before exporting approved vertical or square clips.",
      bestFor: "Podcasts, interviews, webinars, tutorials, founder content, and YouTube repurposing.",
      input: "An owned long-form video and the analysis model you want to use.",
      output: "Editable short-form clips with captions and 9:16, 1:1, or 16:9 delivery options.",
    },
    intro: "Upload a recording once, choose the analysis model, and use scene, transcript, silence, and highlight suggestions to build short-form cuts without surrendering timeline control.",
    primaryHref: "/login?mode=signup",
    primaryLabel: "Upload a long video",
    featureHref: "/clipper",
    outcomes: [
      "Ranked highlight and hook suggestions",
      "Editable transcripts and word-timed captions",
      "9:16, 1:1, and 16:9 delivery formats",
      "Durable processing for large uploads",
    ],
    steps: [
      "Upload a podcast, interview, webinar, tutorial, or campaign recording.",
      "Choose Clipper Autopilot, GPT-5 mini, Gemini, or the local analysis option.",
      "Review suggested highlights, silence, fillers, captions, and reframing.",
      "Keep full editorial control, then export a channel-ready MP4 master.",
    ],
    useCases: ["Podcast clips", "Founder interviews", "Webinar highlights", "YouTube-to-Reels workflows"],
    faq: [
      { question: "Does Editing App automatically publish the clips?", answer: "No. The current workflow prepares private, editable exports so you can approve every cut before publishing." },
      { question: "Does AI permanently cut the original video?", answer: "No. Analysis produces suggestions. Your source remains private and your trim, caption, crop, and audio decisions stay editable." },
      { question: "Which short-form formats are supported?", answer: "Projects can be prepared for vertical 9:16, square 1:1, and landscape 16:9 outputs used across TikTok, Reels, Shorts, Facebook, and YouTube." },
      { question: "Can I choose the analysis model?", answer: "Yes. Use Clipper Autopilot or an approved GPT, Gemini, or local analysis option before running analysis." },
    ],
  },
  {
    slug: "ai-video-generator",
    eyebrow: "AI video generator",
    seoTitle: "AI Video Generator for Marketing Creative",
    title: "AI video generator with premium model choice and production controls",
    description: "Generate cinematic, commercial, and social video from text with selectable Seedance, LTX, Veo, and Kling models, compatible controls, and private delivery.",
    keywords: ["AI video generator", "text to video AI", "multi-model AI video generator", "cinematic AI video", "AI marketing video generator"],
    answer: {
      question: "Which AI video generator should I use for marketing creative?",
      summary: "Use a generator that exposes model, duration, resolution, aspect ratio, camera, and audio limits before rendering. Editing App lets you choose a compatible premium model or use Model Autopilot instead of hiding every request behind one generic route.",
      bestFor: "Product launches, social campaigns, cinematic concepts, brand films, agency production, and commercial shot exploration.",
      input: "A text production brief with subject, action, setting, camera, mood, aspect ratio, duration, resolution, and optional audio direction.",
      output: "A private model-compatible video master with the selected model and production settings recorded.",
    },
    intro: "Start with the shot you need, then choose the model that can actually deliver it. The studio exposes compatible duration, resolution, aspect, camera, and native-audio controls before a paid generation begins.",
    primaryHref: "/login?mode=signup",
    primaryLabel: "Generate an AI video",
    featureHref: "/generate/video",
    outcomes: [
      "Selectable Seedance, LTX, Veo, and Kling routes",
      "Text-to-video direction for camera, mood, format, and audio",
      "Compatibility checks before a paid provider request",
      "Private, retry-safe generation delivery",
    ],
    steps: [
      "Describe the subject, action, setting, camera move, and visual mood.",
      "Choose a compatible premium model or let Model Autopilot route the shot.",
      "Set only the duration, resolution, aspect, and audio options the model supports.",
      "Review and download the private video master when the durable job completes.",
    ],
    useCases: ["Product launch shots", "Social campaign videos", "Cinematic concepts", "Agency creative tests"],
    faq: [
      { question: "Can I choose the AI video model?", answer: "Yes. Choose an approved Seedance, LTX, Veo, or Kling route, or use Model Autopilot for a compatibility-aware recommendation." },
      { question: "Does every model support 4K and long clips?", answer: "No. Model limits differ. Editing App changes the available duration, resolution, aspect, and audio controls to match the selected route." },
      { question: "Can the video include generated audio?", answer: "Yes, when the selected model supports native audio. Audio controls stay unavailable for incompatible models." },
      { question: "How are paid renders protected from duplicate retries?", answer: "Durable job checkpoints record provider submission and delivery so a delivery retry does not silently start the same paid generation again." },
    ],
  },
  {
    slug: "image-to-video-ai",
    eyebrow: "Image to video AI",
    seoTitle: "Image to Video AI Generator for Photos",
    title: "Turn a photo into a directed AI video with source fidelity",
    description: "Animate a photo, product image, artwork, or campaign frame with image-to-video AI, camera direction, identity lock, optional end frames, and premium models.",
    keywords: ["image to video AI", "AI image to video generator", "photo to video AI", "animate image with AI", "product image animation"],
    answer: {
      question: "How do you turn an image into an AI video?",
      summary: "Upload a private start image, describe only the motion and camera direction, choose a compatible model, and optionally add an end frame. Editing App preserves the source as the visual reference while validating duration, resolution, aspect, audio, and transition support.",
      bestFor: "Product reveals, campaign art, portraits, character shots, landscapes, concept frames, and first-to-last-frame transitions.",
      input: "A start image, optional end image, motion brief, camera direction, style, motion intensity, and a compatible model or Autopilot.",
      output: "A privately delivered MP4 that animates the source image with recorded model and motion settings.",
    },
    intro: "Animate the frame you already like without rewriting its entire visual identity. Direct movement, camera, pacing, and optional first-to-last-frame transitions while the source image remains the creative reference.",
    primaryHref: "/login?mode=signup",
    primaryLabel: "Animate an image",
    featureHref: "/generate/image-to-video",
    outcomes: [
      "Premium Seedance, Veo, Kling, and LTX image-to-video routes",
      "Identity and product-detail preservation direction",
      "Optional first-to-last-frame transitions on compatible models",
      "Camera, motion intensity, aspect ratio, and native-audio controls",
    ],
    steps: [
      "Upload a private start image and, when needed, an optional end frame.",
      "Describe motion, camera direction, pacing, and the details that must stay unchanged.",
      "Choose a compatible model or use Motion Autopilot for a supported route.",
      "Review the private animated result and download the completed MP4.",
    ],
    useCases: ["Product animation", "Portrait motion", "Campaign art", "First-to-last-frame transitions"],
    faq: [
      { question: "Which image-to-video models can I choose?", answer: "The studio includes approved Seedance, Veo, Kling, and LTX routes plus Motion Autopilot, subject to current provider availability." },
      { question: "Can I control the first and last frame?", answer: "Yes. Add an optional end frame and the studio limits routing to models that support first-to-last-frame generation." },
      { question: "How does the app preserve my product or subject?", answer: "Identity lock adds explicit source-of-truth direction for faces, product design, colors, proportions, materials, visible text, and scene continuity." },
      { question: "Can every model generate 4K or a long clip?", answer: "No. The interface and server only allow duration, resolution, aspect, audio, and end-frame combinations supported by the selected model." },
    ],
  },
  {
    slug: "ai-image-generator",
    eyebrow: "AI image generator",
    seoTitle: "AI Image Generator for Product Ads",
    title: "AI image generator for product, campaign, and brand visuals",
    description: "Create product photos, ad concepts, editorial images, and brand visuals with premium AI image models, art direction, canvas controls, seeds, and private output.",
    keywords: ["AI image generator", "AI product image generator", "AI ad image generator", "AI marketing image generator", "product photo AI"],
    answer: {
      question: "What can an AI image generator create for a business?",
      summary: "It can produce product scenes, campaign concepts, paid-social graphics, editorial visuals, and brand explorations from a controlled brief. Editing App adds explicit model, canvas, art direction, and seed controls so the result is easier to repeat and review.",
      bestFor: "Ecommerce product visuals, social campaigns, editorial concepts, brand design, and creative testing.",
      input: "A visual brief, canvas, art direction, optional seed, and a selected image model or Image Autopilot.",
      output: "A privately delivered campaign image generated with the chosen compatible model and settings.",
    },
    intro: "Move beyond a generic prompt box. Choose the image model, canvas, art direction, and seed that fit the job, then keep the generated result private while you review the campaign direction.",
    primaryHref: "/login?mode=signup",
    primaryLabel: "Generate an AI image",
    featureHref: "/generate/image",
    outcomes: [
      "Premium Seedream, Recraft, Nano Banana, and FLUX routes",
      "Product, editorial, photoreal, cinematic, and illustrated direction",
      "Canvas, seed, and art-direction controls",
      "Private source and output delivery",
    ],
    steps: [
      "Describe the subject, setting, composition, lighting, materials, and campaign goal.",
      "Choose a premium image model or let Image Autopilot recommend a route.",
      "Set the canvas, art direction, and optional seed for repeatable exploration.",
      "Review and download the private generated image.",
    ],
    useCases: ["Product photography", "Paid-social concepts", "Editorial visuals", "Brand exploration"],
    faq: [
      { question: "Can I choose a specific AI image model?", answer: "Yes. Choose an approved Seedream, Recraft, Nano Banana, or FLUX route, or use Image Autopilot for a fresh routing decision." },
      { question: "Can I create product and advertising images?", answer: "Yes. Product scenes, campaign concepts, social graphics, and commercial art direction are supported, but factual claims should come from your real product information." },
      { question: "Can I control the canvas and creative direction?", answer: "Yes. The brief includes canvas, style, art direction, and optional seed controls instead of relying on one unexplained prompt." },
      { question: "Are generated images public?", answer: "No. Inputs and completed outputs use private storage with time-limited access links." },
    ],
  },
  {
    slug: "product-photo-background-remover",
    eyebrow: "Product background remover",
    seoTitle: "Product Photo Background Remover Online",
    title: "Remove product photo backgrounds with clean, transparent edges",
    description: "Remove backgrounds from product photos, portraits, and catalog images with precision or speed AI models, private uploads, edge-aware matting, and transparent PNG output.",
    keywords: ["product photo background remover", "AI background remover", "remove image background", "transparent PNG maker", "ecommerce background remover"],
    answer: {
      question: "What is the best way to remove a product photo background?",
      summary: "Upload a clean JPEG, PNG, or WebP, choose precision for hair and fine product edges or speed for simple subjects, then review the transparent PNG at full size. Editing App keeps source and result files private and uses edge-aware model routing.",
      bestFor: "Ecommerce products, catalogs, marketplace listings, portraits, thumbnails, and campaign cutouts.",
      input: "A private JPEG, PNG, or WebP image and a precision, speed, or Autopilot choice.",
      output: "A private transparent PNG with edge-aware foreground separation.",
    },
    intro: "Prepare product and portrait cutouts without hiding the quality choice. Use a precision route for fine edges or a faster route for clean, simple subjects, then download a transparent PNG for your listing or campaign.",
    primaryHref: "/login?mode=signup",
    primaryLabel: "Remove a background",
    featureHref: "/remove-background",
    outcomes: [
      "Precision matting for hair, soft detail, and product edges",
      "Fast removal for simple, high-contrast subjects",
      "JPEG, PNG, and WebP source validation",
      "Private transparent PNG delivery",
    ],
    steps: [
      "Upload a JPEG, PNG, or WebP product photo or portrait.",
      "Choose precision, speed, or let Background Autopilot select the route.",
      "Run the private cutout job and inspect fine edges at full size.",
      "Download the transparent PNG for ecommerce, design, or campaign use.",
    ],
    useCases: ["Ecommerce listings", "Product catalogs", "Portrait cutouts", "Campaign composites"],
    faq: [
      { question: "Which model should I choose for a product photo?", answer: "Use the precision route for hair, translucent materials, soft product detail, and complex edges; use the speed route for clean, simple subjects; or let Autopilot decide." },
      { question: "What output format is delivered?", answer: "The completed cutout is stored privately and delivered as a transparent PNG." },
      { question: "Which image formats can I upload?", answer: "The background-removal workflow accepts validated JPEG, PNG, and WebP source images." },
      { question: "Are the original and cutout images public?", answer: "No. Source files and completed results stay in private storage and are accessed through short-lived signed links." },
    ],
  },
] as const;

export const comparisonPages = [
  {
    slug: "editing-app-vs-veed",
    competitor: "VEED",
    competitorUrl: "https://www.veed.io/tools/video-editor",
    seoTitle: "Editing App vs VEED: AI Video Tools",
    title: "Editing App vs VEED: AI video creation and editing compared",
    description: "Compare Editing App and VEED for AI video generation, browser editing, model choice, product ads, background processing, and publishing workflows.",
    summary: "VEED is a mature all-in-one editor with collaboration, avatars, translation, and a broad publishing workflow. Editing App is the more focused choice when explicit model selection, private generation delivery, source-aware product ads, and visible model limits matter most.",
    editingAppBestFor: "Creators and agencies that want explicit model choice, private jobs, capability-aware routing, and one workflow for editing, generation, images, ads, and cutouts.",
    competitorBestFor: "Teams that prioritize a mature browser editor, collaboration, avatars, translation, stock media, and broad publishing features.",
    rows: [
      { criterion: "AI video models", editingApp: "Selectable Seedance, LTX, Veo, and Kling routes plus compatibility-aware Autopilot", competitor: "Multiple leading AI models inside a broad video suite" },
      { criterion: "AI clipping", editingApp: "Selectable analysis models with ranked moments, transcript, captions, and editable clip ranges", competitor: "Text-based editing, Auto Edits, captions, cleanup, and B-roll tools" },
      { criterion: "Product URL ads", editingApp: "Source-aware workflow with claim guardrails and platform controls", competitor: "General AI generation and marketing-video workflows" },
      { criterion: "Delivery architecture", editingApp: "Durable background jobs, private storage, and paid-render delivery checkpoints", competitor: "Cloud editor and team workspace" },
      { criterion: "Best-known strength", editingApp: "Transparent model choice and specialized creative routing", competitor: "Breadth, collaboration, translation, avatars, and publishing" },
    ],
  },
  {
    slug: "editing-app-vs-creatify",
    competitor: "Creatify",
    competitorUrl: "https://creatify.ai/features",
    seoTitle: "Editing App vs Creatify: AI Ad Tools",
    title: "Editing App vs Creatify: product URL video ads compared",
    description: "Compare Editing App and Creatify for product URL ads, ecommerce creative, AI avatars, model choice, AI clipping, and source-aware generation.",
    summary: "Creatify specializes in scalable performance ads, avatars, voices, and creative intelligence. Editing App combines product-URL creative with AI clipping, multi-model video and image generation, private processing, and explicit provider controls.",
    editingAppBestFor: "Small brands and agencies that want product ads plus hands-on editing, model selection, image generation, background removal, and private media jobs in one workspace.",
    competitorBestFor: "Advertisers that prioritize high-volume avatar-led UGC workflows, voice libraries, batch production, and competitor-ad intelligence.",
    rows: [
      { criterion: "Product URL workflow", editingApp: "Extracts source context and blocks unsupported product claims", competitor: "Flagship URL-to-video workflow for marketing ads" },
      { criterion: "Video model control", editingApp: "Named Seedance and Veo ad directors with visible capability limits", competitor: "Outcome-led generation workflow with less emphasis on provider selection" },
      { criterion: "AI avatars and voices", editingApp: "Not a current core feature", competitor: "Custom avatars, AI influencers, AI humans, and a large voice library" },
      { criterion: "AI clipping", editingApp: "Video-link or upload input with ranked moments, transcript, captions, crops, and private exports", competitor: "Primarily performance-ad production and editing" },
      { criterion: "Private processing", editingApp: "Private storage, signed delivery URLs, and durable jobs", competitor: "Cloud performance-creative platform" },
    ],
  },
  {
    slug: "editing-app-vs-opusclip",
    competitor: "OpusClip",
    competitorUrl: "https://www.opus.pro/",
    seoTitle: "Editing App vs OpusClip: Video Clipping",
    title: "Editing App vs OpusClip: long video to shorts compared",
    description: "Compare Editing App and OpusClip for turning long videos into shorts, highlight discovery, captions, reframing, model selection, editing, and publishing.",
    summary: "OpusClip is a specialist in automatic clipping and one-click social publishing. Editing App keeps the cut editable and extends the same workspace into premium video generation, image generation, product ads, and background removal.",
    editingAppBestFor: "Editors and agencies that want AI suggestions with timeline control, selectable analysis, private projects, and adjacent generation tools.",
    competitorBestFor: "High-volume creators who prioritize automatic clipping, virality scoring, supported-link ingestion, and direct social publishing.",
    rows: [
      { criterion: "Highlight discovery", editingApp: "Selectable analysis agents produce editable scene and highlight suggestions", competitor: "Specialized automatic clipping and virality-focused ranking" },
      { criterion: "Editorial control", editingApp: "Transcript, captions, crop, cleanup, and timeline decisions remain editable", competitor: "Automation-first clip workflow with an integrated editor" },
      { criterion: "Publishing", editingApp: "Exports private masters for manual approval and publishing", competitor: "One-click publishing to supported social platforms" },
      { criterion: "Generative media", editingApp: "Video, image, product-ad, and background-removal model menus", competitor: "Long-video repurposing is the central product" },
      { criterion: "Best-known strength", editingApp: "One private edit-and-generate workspace", competitor: "Fast, high-volume long-video repurposing" },
    ],
  },
] as const;

export type SearchIntentPage = (typeof searchIntentPages)[number];
export type ComparisonPage = (typeof comparisonPages)[number];

export function getSearchIntentPage(slug: string) {
  return searchIntentPages.find((page) => page.slug === slug);
}

export function getComparisonPage(slug: string) {
  return comparisonPages.find((page) => page.slug === slug);
}
